# DATA PRE-PROCESSING IN NATURAL LANGUAGE PROCESSING (NLP)

Data source: https://www.kaggle.com/datasets/mrisdal/fake-news

CASE considered-> Fake news detection project: The pre-processing part

In [1]:
#IMPORTING LIBRARIES FOR GENERAL NLP

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
from array import *
import functools

In [2]:
#DOWNLOADING STOPWORDS

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [3]:
#IMPORTING PORTERSTEMMER FOR STEMMING

from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [4]:
#GETTING AVAILABLE DATASET  : fake.csv

dataset = pd.read_csv("fake.csv")
dataset.tail()

,uuid,ord_in_thread,author,published,title,text,language,crawled,site_url,country,domain_rank,thread_title,spam_score,main_img_url,replies_count,participants_count,likes,comments,shares,type
12994,f1b5d0e44803f48732bde854a9fdf95837219b12,2,replaceme,2016-10-26T23:58:00.000+03:00,NaN,It DOES allow you to put a dog face on top of ...,english,2016-10-27T00:37:46.194+03:00,zerohedge.com,US,2435.0,"Snapchat To Raise Up To $4 Billion In IPO, Val...",0.0,NaN,40,32,0,0,0,bs
12995,36011ceba3647e1bea78299b68b6fb705a1fc1ad,3,Freedumb,2016-10-27T00:02:00.000+03:00,NaN,Wait till you see what happens to the valuatio...,english,2016-10-27T00:37:46.220+03:00,zerohedge.com,US,2435.0,"Snapchat To Raise Up To $4 Billion In IPO, Val...",0.0,NaN,40,32,0,0,0,bs
12996,6995d1aa9ac99926106489b14b5530e85358059a,4,major major maj...,2016-10-27T00:06:00.000+03:00,NaN,I'm waiting for the one that puts a pussy on m...,english,2016-10-27T00:37:46.244+03:00,zerohedge.com,US,2435.0,"Snapchat To Raise Up To $4 Billion In IPO, Val...",0.0,NaN,40,32,0,0,0,bs
12997,7de8ae90eee164eb756db6c8a3772288e11d7a94,5,beemasters,2016-10-27T00:09:00.000+03:00,NaN,$4 Billion even after they are known to be kee...,english,2016-10-27T00:37:46.247+03:00,zerohedge.com,US,2435.0,"Snapchat To Raise Up To $4 Billion In IPO, Val...",0.0,NaN,40,32,0,0,0,bs
12998,dabef7095b7d9dae6eb0d83c4cbb40b85efd7ae5,6,i&#039;m-confused,2016-10-27T00:09:00.000+03:00,NaN,of course - how else would they disceminate te...,english,2016-10-27T00:37:46.260+03:00,zerohedge.com,US,2435.0,"Snapchat To Raise Up To $4 Billion In IPO, Val...",0.0,NaN,40,32,0,0,0,bs

In [5]:
dataset.columns

Index(['uuid', 'ord_in_thread', 'author', 'published', 'title', 'text',
       'language', 'crawled', 'site_url', 'country', 'domain_rank',
       'thread_title', 'spam_score', 'main_img_url', 'replies_count',
       'participants_count', 'likes', 'comments', 'shares', 'type'],
      dtype='object')

In [6]:
dataset.shape

(12999, 20)

In [7]:
#DROPPING NaN values to get a cleaned- up dataset

dataset.dropna(axis=0, inplace=True)
dataset.reset_index(inplace= True)
dataset.tail()

,index,uuid,ord_in_thread,author,published,title,text,language,crawled,site_url,...,domain_rank,thread_title,spam_score,main_img_url,replies_count,participants_count,likes,comments,shares,type
4697,12894,a86892dc5a1eb8449a8af935ac38d37a33f896b9,0,Edmondo Burr,2016-11-01T04:15:00.000+02:00,Freddy Krueger Escapes Shooting – Injures Five...,"Posted on October 31, 2016 by Edmondo Burr in ...",english,2016-11-01T14:18:33.484+02:00,yournewswire.com,...,43665.0,Freddy Krueger Escapes Shooting – Injures Five...,0.0,http://cdns.yournewswire.com/wp-content/upload...,0,1,0,0,0,bs
4698,12895,5dccfc016f529eb3aa243de4d2921893efe07914,0,Carol Adl,2016-11-01T04:04:00.000+02:00,UN & Amnesty Investigate Human Rights Violatio...,"Posted on October 31, 2016 by Carol Adl in New...",english,2016-11-01T14:18:34.252+02:00,yournewswire.com,...,43665.0,UN & Amnesty Investigate Human Rights Violatio...,0.0,http://cdns.yournewswire.com/wp-content/upload...,0,1,0,0,0,bs
4699,12896,2ea6ac312a95c472351f8278f5b89a9070009bf5,0,Edmondo Burr,2016-11-01T18:15:25.323+02:00,Turkish Military Deploy Tanks And Equipment To...,"Posted on November 1, 2016 by Edmondo Burr in ...",english,2016-11-01T18:15:25.323+02:00,yournewswire.com,...,43665.0,Turkish Military Deploy Tanks And Equipment To...,0.0,http://cdns.yournewswire.com/wp-content/upload...,0,1,0,0,0,bs
4700,12897,c38ae8b746f70c6a262bf37822829f4cc31bddbd,0,Edmondo Burr,2016-11-01T18:15:25.543+02:00,Australia Is Worried Foreign Migrants Are Coming,Sputnik reports: \nAustralian Prime Minister M...,english,2016-11-01T18:15:25.543+02:00,yournewswire.com,...,43665.0,Australia Is Worried Foreign Migrants Are Coming,0.0,http://cdns.yournewswire.com/wp-content/upload...,0,1,0,0,0,bs
4701,12898,b0e260ae5f45a4ecb9d953e55414f157fa5fbccc,0,Carol Adl,2016-11-01T18:15:26.065+02:00,Johnson & Johnson Lose Third Multimillion Doll...,Johnson & Johnson Lose Third Multimillion Doll...,english,2016-11-01T18:15:26.065+02:00,yournewswire.com,...,43665.0,Johnson & Johnson Lose Third Multimillion Doll...,0.0,http://cdns.yournewswire.com/wp-content/upload...,0,1,0,0,0,bs

In [12]:
ds_shape=dataset.shape
ds_shape

(4702, 21)

In [20]:
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, ds_shape[0]):
    review = re.sub('[^a-zA-Z0-9]', ' ', dataset['text'][i]) #Removing the punctuation symbols
    review = review.lower() #Converting the textual information to all-lowercase text
    review = review.split()# Splitting the sentence/s into list/s
    ps = PorterStemmer() 
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))] #Removing english stopwords
    review = ' '.join(review) #Joining the list elements together to form a string
    corpus.append(review) #accumuating the strings to create the corpus

In [21]:
#Taking a look at the corpus, created
print(corpus[0])

print pay back money plu interest entir famili everyon came need deport asap take two year bust go anoth group steal govern taxpay group somali stole four million govern benefit 10 month report numer case like one muslim refuge immigr commit fraud scam system way control relat